---
language: python
python: "2.7"

addons:
  apt:
    packages:
      - curl

sudo: required

addons:
  apt:
    packages:
      - curl

sudo: required

before_install:
  - pwd
  - "sudo apt-get -y install lsb_release || true"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > /tmp/repo
  - chmod a+x /tmp/repo
  - sudo mv /tmp/repo /bin/repo
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - "[ -d /opt/chaperone ] || sudo mkdir -p /opt/chaperone"

install:
  - pip install ansible ansible-lint

script:
  - cd /tmp
  - echo "y" | repo init -u https://github.com/$TRAVIS_REPO_SLUG -b $TRAVIS_BRANCH -g dev,base
  - repo sync
  - cd ansible/playbooks/ansible
  - ansible-playbook -i inventory ansible.yml
